### ISSUE TITLE
Colombian Catastral Databases

### ISSUE THREAD

**Issue by blaggacao** [GalileoIyS/-gcM-GESTION-CATASTRAL-MULTIPAIS#1]
Just a question: Do you know of (public) catastral databases in Colombia to validate fully specified addresses against?

**Comment by drodrisi** [comment]
Hello, in Colombia the cadastral information is the competence of the IGAC except in certain exceptions and that, as far as we know, it does not publicly offer the information or services that allow us to do reverse geocoding against an address.
Regards

**Comment by blaggacao** [comment]
@drodrisi Thank you very much for that insight.
